# Generated by Django 3.1.1 on 2020-12-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201212_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Foods and drinks', 'Foods and drinks'), ('UnCategorized', 'UnCategorized'), ('Accessories', 'Accessories'), ('Sports', 'Sports'), ('FootWear', 'FootWear'), ('Clothing', 'Clothing'), ('Fashion', 'Fashion'), ('Electronics', 'Electronics'), ('Baby and Kids', 'baby and Kids')], max_length=200, null=True),
        ),
    ]
