# Generated by Django 3.1.1 on 2020-12-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_order_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Admin', 'Admin'), ('Staff', 'Staff'), ('Vendor', 'Vendor'), ('Buyer', 'Buyer')], max_length=200, null=True),
        ),
    ]
