# Generated by Django 3.1.1 on 2020-12-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customer_customer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Admin', 'Admin'), ('Employee', 'Employee'), ('Staff', 'Staff'), ('Vendor', 'Vendor'), ('Buyer', 'Buyer')], max_length=200, null=True),
        ),
    ]
