# Generated by Django 3.1.1 on 2020-12-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20201213_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('customer_type', models.CharField(choices=[('Customer', 'Customer'), ('Admin', 'Admin'), ('Employee', 'Employee'), ('Staff', 'Staff'), ('Vendor', 'Vendor'), ('Buyer', 'Buyer')], max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_type',
        ),
    ]
