# Generated by Django 3.1.1 on 2020-12-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201213_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='customer_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Employee', 'Employee'), ('Staff', 'Staff')], max_length=200, null=True),
        ),
    ]
